### PR TITLE
(fix): Library fixes

### LINKED ISSUE #8: (bug): Throwing error when calling js-combinatorics methods
Actually the library is throwing errors when using the `js-combinatorics` API incorrectly (or like it would be in an older version of `js-combinatorics`).

```sh
/home/armando/Projects/giganto-api/service/node_modules/patronus/lib/internalUse.js:300
        combos = combinatorics.power(optional).map(function (combo) {
                              ^

TypeError: Cannot read property 'power' of undefined
    at Object.internals.getCombos (/home/armando/Projects/giganto-api/service/node_modules/patronus/lib/internalUse.js:300:31)
    at Object.internals.testsFromHapiRoute (/home/armando/Projects/giganto-api/service/node_modules/patronus/lib/internalUse.js:37:32)
    at /home/armando/Projects/giganto-api/service/node_modules/patronus/lib/Patronus.js:80:47
    at Array.forEach (native)
    at /home/armando/Projects/giganto-api/service/node_modules/patronus/lib/Patronus.js:78:19
    at Array.forEach (native)
    at Object.exports.testsFromRoute (/home/armando/Projects/giganto-api/service/node_modules/patronus/lib/Patronus.js:71:21)
    at Suite.<anonymous> (/home/armando/Projects/giganto-api/service/test/e2e/health/health.js:28:30)
    at Object.create (/home/armando/Projects/giganto-api/service/node_modules/mocha/lib/interfaces/common.js:114:19)
    at Object.only (/home/armando/Projects/giganto-api/service/node_modules/mocha/lib/interfaces/common.js:79:21)
    at Function.context.describe.only (/home/armando/Projects/giganto-api/service/node_modules/mocha/lib/interfaces/bdd.js:68:27)
    at Object.<anonymous> (/home/armando/Projects/giganto-api/service/test/e2e/health/health.js:27:10)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/armando/Projects/giganto-api/service/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at /home/armando/Projects/giganto-api/service/node_modules/mocha/lib/mocha.js:222:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/armando/Projects/giganto-api/service/node_modules/mocha/lib/mocha.js:219:14)
    at Mocha.run (/home/armando/Projects/giganto-api/service/node_modules/mocha/lib/mocha.js:487:10)
    at Object.<anonymous> (/home/armando/Projects/giganto-api/service/node_modules/mocha/bin/_mocha:458:18)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/armando/Projects/giganto-api/service/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Function.Module.runMain (module.js:607:10)
    at runFn (/home/armando/Projects/giganto-api/service/node_modules/istanbul/lib/command/common/run-with-cover.js:122:16)
    at /home/armando/Projects/giganto-api/service/node_modules/istanbul/lib/command/common/run-with-cover.js:251:17
    at /home/armando/Projects/giganto-api/service/node_modules/istanbul/lib/util/file-matcher.js:68:16
    at /home/armando/Projects/giganto-api/service/node_modules/async/lib/async.js:52:16
    at /home/armando/Projects/giganto-api/service/node_modules/async/lib/async.js:361:13
    at /home/armando/Projects/giganto-api/service/node_modules/async/lib/async.js:52:16
    at done (/home/armando/Projects/giganto-api/service/node_modules/async/lib/async.js:246:17)
    at /home/armando/Projects/giganto-api/service/node_modules/async/lib/async.js:44:16
    at /home/armando/Projects/giganto-api/service/node_modules/async/lib/async.js:358:17
    at LOOP (fs.js:1611:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! Test failed.  See above for more details.
```

### PR DESCRIPTION
**Pull request by armand1m**
These commits:

 - Fixes #8
 - Upgrades dependencies
 - Fixes unit test cases
 - Improves if statement of settings.response.schema (was leading to failure in most scenarios)

### CODE REVIEW

**Comment by mattapperson** [comment]
Unit tests fail

**Comment by armand1m** [comment]
Actually it seems to fail because Node v0.12 doesn't support `const` statements, used in the updated dependencies.. There are any plans of upgrading the tests to use Node v4+ ?

**Comment by mattapperson** [comment]
If you want to give a shot to updating the node version and ensuring tests pass on node v4 and v6 I'm happy to merge it

**Comment by armand1m** [comment]
Ok I will submit another one

**Comment by mattapperson** [comment]
Thanks!

**Comment by armand1m** [comment]
@mattapperson Just one question, the npm package will be updated automatically or it depends on your publishing?

**Comment by mattapperson** [comment]
published

**Pull request merged**
